apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: authorizer-app1
  tags:
    - dotnet
    - microservice
spec:
  type: service
  lifecycle: production
  owner: authorizer-team
  system: authorization